### ISSUE TITLE
cog.py

### ISSUE THREAD

**Issue by augre** [rwestenberger/MicroMegas-Simulation#1]
MicroMegas-Simulation/simulation/build$ make
[  5%] Cogging source files...
make[2]: cog.py: Command not found
make[2]: **\* [/home/medphys/bin/MicroMegas-Simulation/simulation/photoconversion/photoconversion.cpp] Error 127
make[1]: **\* [CMakeFiles/CogFiles.dir/all] Error 2
make: **\* [all] Error 2

**Comment by rwestenberger** [comment]
You will need to install [cog](https://pypi.python.org/pypi/cogapp/2.4) to build the simulation and/or make it reachable by your shell.
Cog is used for C++ code generation from the configuration file.

**Comment by augre** [comment]
MicroMegas-Simulation/simulation/build$ make
[  5%] Cogging source files...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cogapp/cogapp.py", line 714, in main
    self.callableMain(argv)
  File "/usr/local/lib/python2.7/dist-packages/cogapp/cogapp.py", line 705, in callableMain
    self.processArguments([a])
  File "/usr/local/lib/python2.7/dist-packages/cogapp/cogapp.py", line 679, in processArguments
    self.processOneFile(args[0])
  File "/usr/local/lib/python2.7/dist-packages/cogapp/cogapp.py", line 628, in processOneFile
    sNewText = self.processString(sOldText, fname=sFile)
  File "/usr/local/lib/python2.7/dist-packages/cogapp/cogapp.py", line 567, in processString
    self.processFile(fOld, fNew, fname=fname)
  File "/usr/local/lib/python2.7/dist-packages/cogapp/cogapp.py", line 507, in processFile
    sGen = gen.evaluate(cog=self, globals=globals, fname=sFile)
  File "/usr/local/lib/python2.7/dist-packages/cogapp/cogapp.py", line 147, in evaluate
    eval(code, globals)
  File "/home/medphys/bin/MicroMegas-Simulation/simulation/photoconversion/photoconversion.cpp+46", line 2, in <module>
ImportError: No module named MMconfig
make[2]: **\* [/home/medphys/bin/MicroMegas-Simulation/simulation/photoconversion/photoconversion.cpp] Error 1
make[1]: **\* [CMakeFiles/CogFiles.dir/all] Error 2
make: **\* [all] Error 2

**Comment by rb815815** [comment]
Hello, I meet a compiling problem like this.

[ 37%] Building CXX object CMakeFiles/photoconversion.dir/src/EventAction.cpp.o
[ 43%] Building CXX object CMakeFiles/photoconversion.dir/src/OutputManager.cpp.o
[ 50%] Building CXX object CMakeFiles/photoconversion.dir/src/PhysicsList.cpp.o
/home/thy/MicroMegas-Simulation/simulation/photoconversion/src/PhysicsList.cpp: In member function ‘void PhysicsList::AddDecay()’:
/home/thy/MicroMegas-Simulation/simulation/photoconversion/src/PhysicsList.cpp:95:3: error: ‘theParticleIterator’ was not declared in this scope; did you mean ‘GetParticleIterator’?
   95 |   theParticleIterator->reset();

I guess it is caused by a higher version of geant4 (v4.10.4) that I use, so I want to know which version of geant4 was used in this project?
